apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-apps-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: sl-rewrite@kubernetescrd
    
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.auth.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.auth.name }}
                port:
                  number: {{ .Values.auth.service.port }}
          - path: {{ .Values.profiles.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.profiles.name }}
                port:
                  number: {{ .Values.profiles.service.port }}

